import type { Job } from '../types/job'

export const mockJobs: Job[] = [
  {
    id: 'job-001',
    clinicId: 'clinic-001',
    clinicName: 'スマイル歯科クリニック',
    title: '歯科衛生士（正社員）｜渋谷駅徒歩3分・残業ほぼなし',
    jobType: '歯科衛生士',
    employmentType: '正社員',
    prefecture: '東京都',
    city: '渋谷区',
    address: '渋谷区道玄坂1-2-3 渋谷ビル4F',
    salaryMin: 260000,
    salaryMax: 340000,
    salaryType: '月給',
    description:
      '渋谷駅から徒歩3分、アクセス抜群のスマイル歯科クリニックで歯科衛生士を募集しています。当院は予防歯科に特化したクリニックで、患者さまとの長期的な信頼関係を大切にしています。スタッフ同士の仲が良く、働きやすい環境を整えています。産休・育休取得実績もあり、ライフイベントに合わせた働き方が可能です。',
    requirements: [
      '歯科衛生士免許をお持ちの方',
      '経験年数不問（新卒歓迎）',
      '明るく患者さまに丁寧に接することができる方',
      'チームワークを大切にできる方',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '制服貸与',
      '産休・育休取得実績あり',
      '研修制度充実',
      '資格取得支援制度',
      '昇給年1回',
      '賞与年2回',
    ],
    workingHours: '9:00〜18:00（休憩1時間）／木曜・日曜午後は17:00まで',
    holidays: '日曜・祝日、木曜午後、夏季休暇、年末年始',
    postedAt: '2026-03-01',
    deadline: '2026-04-30',
    isActive: true,
    viewCount: 312,
    applicationCount: 8,
    images: [],
  },
  {
    id: 'job-002',
    clinicId: 'clinic-002',
    clinicName: 'さくら歯科医院',
    title: '歯科医師（常勤）｜インプラント・矯正経験者歓迎',
    jobType: '歯科医師',
    employmentType: '正社員',
    prefecture: '大阪府',
    city: '大阪市北区',
    address: '大阪市北区梅田2-4-9 ヒルトンプラザウエスト5F',
    salaryMin: 700000,
    salaryMax: 1200000,
    salaryType: '月給',
    description:
      '梅田駅直結・アクセス最高のさくら歯科医院では、常勤歯科医師を募集しています。一般歯科はもちろん、インプラントや矯正歯科にも注力しており、最新機器を揃えた設備で高度な治療を提供しています。若手からベテランまで幅広いスタッフが活躍中。院長によるサポート体制が整っており、スキルアップできる環境です。年収1000万円以上も可能です。',
    requirements: [
      '歯科医師免許をお持ちの方',
      '臨床経験3年以上',
      'インプラントまたは矯正の経験・資格があれば尚可',
      '患者さまに真摯に向き合える方',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '学会参加費用補助',
      '技工料補助',
      '駐車場あり',
      '賞与年2回',
      '昇給年1回',
    ],
    workingHours: '9:00〜19:00（休憩1時間）',
    holidays: '火曜、日曜・祝日、夏季休暇3日、年末年始5日',
    postedAt: '2026-02-15',
    deadline: '2026-05-31',
    isActive: true,
    viewCount: 521,
    applicationCount: 14,
    images: [],
  },
  {
    id: 'job-003',
    clinicId: 'clinic-003',
    clinicName: 'みなとみらい歯科',
    title: '歯科衛生士（パート）｜週3日〜OK・時間相談可',
    jobType: '歯科衛生士',
    employmentType: 'パート・アルバイト',
    prefecture: '神奈川県',
    city: '横浜市西区',
    address: '横浜市西区みなとみらい3-5-1 マークイズみなとみらい3F',
    salaryMin: 1800,
    salaryMax: 2400,
    salaryType: '時給',
    description:
      'みなとみらい駅徒歩2分の好立地にあるみなとみらい歯科では、パートタイムの歯科衛生士を募集しています。子育て中の方や、プライベートを大切にしながら働きたい方におすすめです。週3日〜勤務可能で、シフトは相談に応じます。経験豊富なスタッフが多く、ブランクがある方もご安心ください。',
    requirements: [
      '歯科衛生士免許をお持ちの方',
      '週3日以上勤務できる方',
      'ブランクがある方も歓迎',
      '子育て中の方も歓迎',
    ],
    benefits: [
      '交通費支給（月2万円まで）',
      '制服貸与',
      '託児所提携あり',
      '有給休暇あり',
      '昇給あり',
    ],
    workingHours: '9:00〜13:00 または 14:00〜18:30（応相談）',
    holidays: '日曜・祝日、水曜午後（シフト制）',
    postedAt: '2026-03-05',
    isActive: true,
    viewCount: 198,
    applicationCount: 5,
    images: [],
  },
  {
    id: 'job-004',
    clinicId: 'clinic-001',
    clinicName: 'スマイル歯科クリニック',
    title: '歯科助手（正社員）｜未経験歓迎・充実した研修制度',
    jobType: '歯科助手',
    employmentType: '正社員',
    prefecture: '東京都',
    city: '渋谷区',
    address: '渋谷区道玄坂1-2-3 渋谷ビル4F',
    salaryMin: 220000,
    salaryMax: 270000,
    salaryType: '月給',
    description:
      '歯科助手として患者さまの対応や診療補助業務をお任せします。未経験の方でも丁寧な研修制度があるので安心してスタートできます。スマイル歯科クリニックはチームワークを大切にしており、先輩スタッフが丁寧にサポートします。将来的に歯科衛生士の資格取得を目指す方への支援制度もあります。',
    requirements: [
      '未経験歓迎',
      '高卒以上',
      '明るく元気な方',
      '人と接することが好きな方',
      '歯科衛生士資格取得を目指している方も歓迎',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '制服貸与',
      '資格取得支援制度',
      '研修制度充実',
      '昇給年1回',
      '賞与年2回',
    ],
    workingHours: '9:00〜18:00（休憩1時間）',
    holidays: '日曜・祝日、木曜午後、年末年始、夏季休暇',
    postedAt: '2026-03-10',
    deadline: '2026-04-30',
    isActive: true,
    viewCount: 145,
    applicationCount: 11,
    images: [],
  },
  {
    id: 'job-005',
    clinicId: 'clinic-004',
    clinicName: 'ホワイトデンタルクリニック',
    title: '受付・医療事務（正社員）｜土日勤務可・経験者優遇',
    jobType: '受付・事務',
    employmentType: '正社員',
    prefecture: '愛知県',
    city: '名古屋市中区',
    address: '名古屋市中区栄3-15-33 栄ガスビル8F',
    salaryMin: 210000,
    salaryMax: 260000,
    salaryType: '月給',
    description:
      '栄駅から徒歩5分のホワイトデンタルクリニックで受付・医療事務スタッフを募集します。患者さまの受付・会計・電話対応・レセプト業務などをお任せします。医療事務の経験がある方を優遇しますが、歯科経験がない方もサポートします。清潔感のある明るい方を歓迎します。',
    requirements: [
      '高卒以上',
      '医療事務経験者優遇（未経験可）',
      'PCスキル（Word・Excel基本操作）',
      '清潔感があり接遇マナーの良い方',
      '土日どちらか勤務できる方',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '制服貸与',
      '医療事務資格取得支援',
      '昇給年1回',
      '賞与年2回',
      '残業少なめ',
    ],
    workingHours: '9:00〜18:00（シフト制、週5日勤務）',
    holidays: '月曜、祝日、年末年始、夏季休暇',
    postedAt: '2026-02-20',
    isActive: true,
    viewCount: 267,
    applicationCount: 19,
    images: [],
  },
  {
    id: 'job-006',
    clinicId: 'clinic-002',
    clinicName: 'さくら歯科医院',
    title: '歯科技工士（正社員）｜最新CAD/CAM設備完備',
    jobType: '歯科技工士',
    employmentType: '正社員',
    prefecture: '大阪府',
    city: '大阪市北区',
    address: '大阪市北区梅田2-4-9 ヒルトンプラザウエスト5F',
    salaryMin: 280000,
    salaryMax: 380000,
    salaryType: '月給',
    description:
      '最新鋭のCAD/CAMシステムを導入したさくら歯科医院附属技工所では、歯科技工士を募集しています。クラウン・ブリッジ・インプラント上部構造・義歯など幅広い技工物の製作に携わることができます。技術向上のための勉強会や外部研修への参加も積極的に支援しています。技工士としてのキャリアを磨きたい方にぴったりの環境です。',
    requirements: [
      '歯科技工士免許をお持ちの方',
      '経験年数不問（新卒歓迎）',
      'CAD/CAM経験者優遇',
      '向上心を持って仕事に取り組める方',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '各種研修参加費補助',
      '最新設備で技術向上可能',
      '昇給年1回',
      '賞与年2回',
    ],
    workingHours: '9:00〜18:00（休憩1時間）',
    holidays: '土曜・日曜・祝日、夏季休暇、年末年始',
    postedAt: '2026-03-08',
    isActive: true,
    viewCount: 89,
    applicationCount: 3,
    images: [],
  },
  {
    id: 'job-007',
    clinicId: 'clinic-005',
    clinicName: 'なかむら矯正歯科',
    title: '歯科衛生士（正社員）｜矯正専門クリニック・スキルアップ環境',
    jobType: '歯科衛生士',
    employmentType: '正社員',
    prefecture: '福岡県',
    city: '福岡市中央区',
    address: '福岡市中央区天神2-3-10 天神パインクレスト7F',
    salaryMin: 240000,
    salaryMax: 320000,
    salaryType: '月給',
    description:
      '矯正歯科専門のなかむら矯正歯科では、歯科衛生士を募集しています。ワイヤー矯正からマウスピース矯正まで多様なケースに関わることができ、矯正のスペシャリストを目指せる環境です。院内勉強会を月2回開催しており、最新の矯正技術を学べます。患者さまの長期にわたる治療をサポートするやりがいのある仕事です。',
    requirements: [
      '歯科衛生士免許をお持ちの方',
      '矯正歯科経験者優遇（未経験可）',
      '患者さまに丁寧に対応できる方',
      '学習意欲の高い方',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '院内外勉強会参加費補助',
      '制服貸与',
      '昇給年1回',
      '賞与年2回',
      '産休・育休取得実績あり',
    ],
    workingHours: '9:30〜18:30（休憩1時間）',
    holidays: '日曜・祝日、木曜、夏季休暇、年末年始',
    postedAt: '2026-03-12',
    deadline: '2026-05-15',
    isActive: true,
    viewCount: 176,
    applicationCount: 6,
    images: [],
  },
  {
    id: 'job-008',
    clinicId: 'clinic-003',
    clinicName: 'みなとみらい歯科',
    title: '歯科医師（非常勤）｜週2日〜・自由診療あり',
    jobType: '歯科医師',
    employmentType: 'パート・アルバイト',
    prefecture: '神奈川県',
    city: '横浜市西区',
    address: '横浜市西区みなとみらい3-5-1 マークイズみなとみらい3F',
    salaryMin: 15000,
    salaryMax: 25000,
    salaryType: '時給',
    description:
      'みなとみらい歯科では非常勤歯科医師を募集しています。一般歯科・小児歯科・審美歯科（ホワイトニング含む）など幅広い診療を行っています。週2日から勤務可能で、他院との掛け持ちも歓迎です。経験豊富な常勤医師とともに診療を行うため、開業準備中の先生にもおすすめです。',
    requirements: [
      '歯科医師免許をお持ちの方',
      '臨床経験2年以上',
      '週2日以上勤務できる方',
      '他院との掛け持ち可',
    ],
    benefits: [
      '交通費支給（上限あり）',
      '駐車場あり',
      '技工費補助',
      '研修参加費補助',
    ],
    workingHours: '9:00〜18:00（応相談）',
    holidays: 'シフト制（週2日〜）',
    postedAt: '2026-02-28',
    isActive: true,
    viewCount: 234,
    applicationCount: 7,
    images: [],
  },
  {
    id: 'job-009',
    clinicId: 'clinic-004',
    clinicName: 'ホワイトデンタルクリニック',
    title: '歯科衛生士（契約社員）｜予防歯科特化・月給28万〜',
    jobType: '歯科衛生士',
    employmentType: '契約社員',
    prefecture: '愛知県',
    city: '名古屋市千種区',
    address: '名古屋市千種区覚王山通9-18 覚王山パークビル2F',
    salaryMin: 280000,
    salaryMax: 330000,
    salaryType: '月給',
    description:
      '予防歯科に力を入れているホワイトデンタルクリニック覚王山院では歯科衛生士を募集しています。SRP・TBIを中心とした予防処置を担当していただきます。担当制を採用しており、患者さまとの継続的な関係構築ができます。スタッフの定着率が高く、長く働きやすい環境です。正社員登用制度あり。',
    requirements: [
      '歯科衛生士免許をお持ちの方',
      '経験1年以上',
      '予防歯科への関心が高い方',
      '患者さまとの信頼関係を大切にできる方',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '制服貸与',
      '正社員登用制度あり',
      '昇給年1回',
      '賞与年1回',
      '研修参加費補助',
    ],
    workingHours: '9:00〜18:00（休憩1時間）',
    holidays: '月曜、日曜・祝日、夏季休暇、年末年始',
    postedAt: '2026-03-03',
    deadline: '2026-04-15',
    isActive: true,
    viewCount: 152,
    applicationCount: 4,
    images: [],
  },
  {
    id: 'job-010',
    clinicId: 'clinic-005',
    clinicName: 'なかむら矯正歯科',
    title: '受付（パート）｜経験不問・笑顔が好きな方歓迎',
    jobType: '受付・事務',
    employmentType: 'パート・アルバイト',
    prefecture: '福岡県',
    city: '福岡市中央区',
    address: '福岡市中央区天神2-3-10 天神パインクレスト7F',
    salaryMin: 1100,
    salaryMax: 1400,
    salaryType: '時給',
    description:
      'なかむら矯正歯科では受付パートスタッフを募集しています。患者さまの受付・電話対応・会計補助などをお任せします。医療・歯科経験がない方も丁寧に研修します。矯正治療中の患者さまと長期にわたる関係を築けるやりがいのあるお仕事です。学生・主婦・フリーターの方も歓迎します。',
    requirements: [
      '経験不問',
      '高校生可（18歳以上）',
      '週3日以上勤務できる方',
      '明るく笑顔で接客できる方',
      'PCの基本操作ができる方',
    ],
    benefits: [
      '交通費支給',
      '制服貸与',
      '社会保険（週30時間以上）',
      '有給休暇あり',
      '昇給あり',
    ],
    workingHours: '9:30〜18:30（シフト制）',
    holidays: '日曜・祝日、木曜（シフトによる）',
    postedAt: '2026-03-15',
    isActive: true,
    viewCount: 98,
    applicationCount: 9,
    images: [],
  },
  {
    id: 'job-011',
    clinicId: 'clinic-001',
    clinicName: 'スマイル歯科クリニック',
    title: '歯科衛生士（正社員）｜新卒・第二新卒歓迎・産育休実績豊富',
    jobType: '歯科衛生士',
    employmentType: '正社員',
    prefecture: '東京都',
    city: '新宿区',
    address: '新宿区新宿3-14-1 伊勢丹会館5F',
    salaryMin: 230000,
    salaryMax: 300000,
    salaryType: '月給',
    description:
      '新宿三丁目駅直結のスマイル歯科クリニック新宿院では歯科衛生士を募集しています。新卒・第二新卒の方も大歓迎です。充実した研修制度とOJTでしっかりとしたスキルが身につきます。産休・育休の取得率100%を誇り、復帰後も時短勤務が可能です。女性が長く活躍できる職場を目指しています。',
    requirements: [
      '歯科衛生士免許をお持ちの方（取得見込みも可）',
      '新卒・第二新卒歓迎',
      '明るくコミュニケーション能力の高い方',
      'ブランクがある方も相談可',
    ],
    benefits: [
      '社会保険完備',
      '交通費全額支給',
      '制服貸与',
      '産休・育休・時短勤務実績あり',
      '研修制度充実',
      '資格取得支援',
      '昇給年1回',
      '賞与年2回',
      '退職金制度',
    ],
    workingHours: '10:00〜19:00（休憩1時間）',
    holidays: '火曜、日曜・祝日、夏季休暇、年末年始',
    postedAt: '2026-03-18',
    deadline: '2026-06-30',
    isActive: true,
    viewCount: 421,
    applicationCount: 17,
    images: [],
  },
  {
    id: 'job-012',
    clinicId: 'clinic-002',
    clinicName: 'さくら歯科医院',
    title: '歯科助手（パート）｜土日のみOK・学生歓迎',
    jobType: '歯科助手',
    employmentType: 'パート・アルバイト',
    prefecture: '大阪府',
    city: '大阪市中央区',
    address: '大阪市中央区心斎橋筋2-1-3 心斎橋OPA8F',
    salaryMin: 1050,
    salaryMax: 1300,
    salaryType: '時給',
    description:
      '心斎橋駅徒歩1分のさくら歯科医院心斎橋院では歯科助手のパートを募集しています。土日のみの勤務もOKで、学生・フリーターの方も歓迎します。診療補助・器具の洗浄・院内清掃などをお任せします。歯科に興味がある方、将来歯科業界で働きたい方にもおすすめです。職場の雰囲気はアットホームで働きやすいと好評です。',
    requirements: [
      '経験不問',
      '高校生可（18歳以上）',
      '土日どちらかのみ勤務可',
      '明るく積極的な方',
    ],
    benefits: [
      '交通費支給',
      '制服貸与',
      '昇給あり',
      '社会保険（条件あり）',
    ],
    workingHours: '9:00〜18:00（土日祝）',
    holidays: '平日全日（土日勤務）',
    postedAt: '2026-03-20',
    isActive: true,
    viewCount: 63,
    applicationCount: 2,
    images: [],
  },
]
